server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #for standalone mode, no need to register to other eureka server
    fetch-registry: false #for standalone mode, no need to fetch info from other eureka server
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/