server:
  port: 9050

spring:
  application:
    name: OrderService

eureka:
  client:
    service-url:
      defaultZone: http://root:1234@localhost:8761/eureka  # http://user:password@ip:port/eureka