server:
  port: 9001

spring:
  application:
    name: AccountService

eureka:
  client:
    service-url:
      defaultZone: http://root:1234@localhost:8761/eureka  # http://user:password@IP:port/eureka